### ISSUE TITLE
Dockerfile generation fails with `Cluster not found for context `k8s.KubeConfigModels.Context` in kubeconfig`

### ISSUE THREAD

**Issue by mmccord-mdbuyline** [buehler/dotnet-operator-sdk#192]
If I generate a new operator using the template, I get the following build failure:

```
Generating Dockerfile
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> k8s.Exceptions.KubeConfigException: Cluster not found for context `k8s.KubeConfigModels.Context` in kubeconfig
   at k8s.KubernetesClientConfiguration.SetClusterDetails(K8SConfiguration k8SConfig, Context activeContext)
   at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigObject(K8SConfiguration k8SConfig, String currentContext, String masterUrl)
   at k8s.KubernetesClientConfiguration.BuildDefaultConfig()
   at DotnetKubernetesClient.KubernetesClient..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ServiceProvider.GetService(Type serviceType)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.System.IServiceProvider.GetService(Type serviceType)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.FindMatchedConstructor[TModel](ConstructorInfo[] constructors, IServiceProvider services, Boolean throwIfNoParameterTypeRegistered)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.ApplyImpl[TModel](ConventionContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.Apply(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Builder.McMaster.Extensions.CommandLineUtils.Conventions.IConventionBuilder.AddConvention(IConvention convention)
   at McMaster.Extensions.CommandLineUtils.ConventionBuilderExtensions.UseConstructorInjection(IConventionBuilder builder, IServiceProvider additionalServices)
   at KubeOps.Operator.HostExtensions.RunOperatorAsync(IHost host, String[] args)
   at CloudFormationStackOperator.Program.Main(String[] args) in <redacted>
   at CloudFormationStackOperator.Program.<Main>(String[] args)
```

**Comment by buehler** [comment]
Hey @mmccord-mdbuyline 
Quick question: do you have any extra fields in the context? Like "non standard" fields that may interfere with the parser?

This sounds like an issue with your `kubeConfig`.

But, in any case, it should not need the kubernetes client to generate the dockerfile.

**Comment by mmccord-mdbuyline** [comment]
No non-standard fields. It reads the kubeconfig fine. Has to do with the fallback mechanism in `BuildDefaultConfig()`. In fact if I add the following fall back mechanism to my `ConfigureServices` method to override the default behavior it works:

```csharp
               bool tryFallback = false;
                try
                {
                    services.TryAddSingleton(KubernetesClientConfiguration.InClusterConfig());
                }
                catch (Exception)
                {
                    tryFallback = true;
                }

                if (tryFallback)
                {
                    try
                    {
                        services.AddSingleton(
                            KubernetesClientConfiguration.BuildConfigFromConfigFile(UserKubeConfigPath, "docker-desktop"));
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }
```


However, obviously this is not ideal, particularly from the stand point of a template that theoretically should work out of the box. I might suggest a different approach for your generators: bundling .NET executables with the nuget package that perform these operations instead of building these operations into the application produced by the template. If you do that you can build out purpose built executables that do not need to even include the kubernetes client.

**Comment by mmccord-mdbuyline** [comment]
Side note... `UserKubeConfigPath` from above looks like this:

```csharp
private static readonly string UserKubeConfigPath =
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".kube", "config");
```

**Comment by buehler** [comment]
I see...
I don't get the point of your suggestion clearly, do you mind explaining which executables you mean?
I use the kubernetes client quite heavily in the operator sdk, so there is no replacing it. I had built a software once that used `kubectl`, but this is error prone as hell when using it over sub-processes.

When we have a look at the method that builds the kube config out of "default":
https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L47-L71

Is any of this "if" 's true on your machine, or can you think of any reason why it does use the wrong config?

The steps are:
1. Check if `KUBECONFIG` environment var is set, if yes, use this file (or multiple files) as config
2. Check if the `<user home>/.kube/config` file exists, if yes, use this file
3. Check if the running app is "in - cluster" (meaning is `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` set, and does the service account token as well as the root ca exist on the machine), if yes, build the kube config inside the cluster
4. use a default location of `http://localhost:8080`

I'm asking this, because - despite the usage of docker and stuff - I've got a classical "works on my machine" problem. I cannot reproduce the error.

BUT, what you could do:
as soon as you added the operator stuff with the `AddKubernetesOperator`, you may remove the transient binding for `IKubernetesClient` and add it with your specific config:

```csharp
services.AddKubernetesOperator();
services.RemoveAll(typeof(IKubernetesClient));
// use your specific config here
services.AddTransient(_ => new KubernetesClient(KubernetesClientConfiguration.BuildConfigFromConfigFile()));
```

**Comment by buehler** [comment]
Did you manage to find something @mmccord-mdbuyline ?

**Comment by erin-allison** [comment]
FWIW, I was able to reproduce by breaking my kubectl config; if the active context is set to use a cluster that isn't defined in the file, it throws this error.

This looks like a non-issue for this project. An issue could be opened on buehler/dotnet-kubernetes-client to change the behavior to match kubectl (which attempts to just connect to localhost:8080), but I prefer it throwing an error like this anyways.

```
apiVersion: v1
clusters:
- cluster:
    server: "https://{{REDACTED}}/"
  name: master
contexts:
- context:
    cluster: InvalidClusterNameHere
    user: admin
  name: master
current-context: master
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: "{{REDACTED}}"
```

```
[2021-05-31T12:42:53.8011607-05:00] [INF] (Controller/Program) Starting up
[2021-05-31T12:42:54.6253442-05:00] [FTL] (Controller/Program/1) Application start-up failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating DotnetKubernetesClient.KubernetesClient.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'KubernetesClient'.
 ---> k8s.Exceptions.KubeConfigException: Cluster not found for context `k8s.KubeConfigModels.Context` in kubeconfig
   at k8s.KubernetesClientConfiguration.SetClusterDetails(K8SConfiguration k8SConfig, Context activeContext)
   at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildDefaultConfig()
   at lambda_method100(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
```
