### ISSUE TITLE
Connection to Snowflake DB fails in operator, but suceeds in integration tests

### ISSUE THREAD

**Issue by anekdoti** [buehler/dotnet-operator-sdk#241]
**Describe the bug**
I am developing an operator with Kubeops that uses [Snowflake Connector for .NET](https://github.com/snowflakedb/snowflake-connector-net) to connect to the cloud database Snowflake. Internally, the connector communicates with Snowflake using a REST API. 

In an integration test running on my development machine, the connection to Snowflake succeeds. However, when running the operator on my local machine (or on a Kubernetes cluster), the connection fails because the Snowflake REST API returns a failing login response - with exactly the same connection string.

As I use the Snowflake connector in exactly the same way in both cases, I wonder whether the configuration of the operator, e.g., the HttpClient used for connecting to Kubernetes, somehow could interfere with the HttpClient used by the Snowflake connector?

**Expected behavior**
A connection to Snowflake succeeds in the same way as in the integration test.

**Additional context**
I am aware of that this does sound like a Snowflake problem instead of a problem with Kubeops. I still would be extremely thankful for any suggestion for something that could differ between trying to connect to a REST API inside a Kubeops operator and outside.

**Comment by erin-allison** [comment]
@anekdoti Can you share the exception message and stack trace it gives you upon failure?

I'm pretty sure neither https://github.com/buehler/dotnet-operator-sdk/ nor https://github.com/buehler/dotnet-kubernetes-client directly touch the HttpClient configuration but if I can see that, maybe I can pull together some code to reproduce and step through the communications.

**Comment by erin-allison** [comment]
Additionally, do you have any service mesh or similar applications deployed in your cluster? Depending on configuration, those could be messing with outbound communication from your controller.

**Comment by anekdoti** [comment]
Hello Erin, thank you very much for your interest and sorry for the late reply.

**Comment by anekdoti** [comment]
Hello Erin, thank you very much for your interest and sorry for the late reply.

In regards to your second message, we do not have anything like a service mesh. I want to point out that the problem already arises when I execute the operator on my local machine und just let it use the API of our Kubernetes cluster - the Snowflake connection should no be affected by the configuration of the cluster. We have a [Kafka Connector for Snowflake](https://docs.snowflake.com/en/user-guide/kafka-connector.html) running in the cluster that connects to Snowflake and uses exactly the same credentials as we do in our integration test and in the operator - and it works perfectly fine.

**Comment by anekdoti** [comment]
In both the operator as well as in the integration test, we try to open a connection to Snowflake using

**Comment by anekdoti** [comment]
In both the operator as well as in the integration test, we try to open a connection to Snowflake using 
```
var conn = new SnowflakeDbConnect { ConnectionString = "..." }; 
await conn.OpenAsync();
```  
For the connection string, we tried different variants: authentication with user/password, key-pair authentication with a decrypted private key in the connection string, key-pair authentication with an encrypted private key in a file referred in the connection string and the decryption key in the connection string - all with the same result, e.g., they fail when executed in a IResourceFinalizer in the operator, but succeed in the integration test, both on my local machine. This is why I think that it does not really have anything to do with the authentication.

The log output of the Snowflake connector is as follows (I pruned some first lines with our credentials):
```
2021-08-12 09:21:46,212 [12] DEBUG Snowflake.Data.Core.SFSessionProperties [(null)] - Sesssion property PORT set to default value: 443
2021-08-12 09:21:46,213 [12] DEBUG Snowflake.Data.Core.SFSessionProperties [(null)] - Sesssion property SCHEME set to default value: https
2021-08-12 09:21:46,214 [12] DEBUG Snowflake.Data.Core.SFSessionProperties [(null)] - Sesssion property CONNECTION_TIMEOUT set to default value: 120
2021-08-12 09:21:46,215 [12] DEBUG Snowflake.Data.Core.SFSessionProperties [(null)] - Sesssion property VALIDATE_DEFAULT_PARAMETERS set to default value: true
2021-08-12 09:21:46,217 [12] DEBUG Snowflake.Data.Core.SFSessionProperties [(null)] - Sesssion property USEPROXY set to default value: false
2021-08-12 09:21:46,237 [12] DEBUG Snowflake.Data.Core.HttpUtil [(null)] - Get Http client for False;;;;;.
2021-08-12 09:21:46,242 [12] DEBUG Snowflake.Data.Core.HttpUtil [(null)] - Http client for False;;;;; not registered. Adding.
2021-08-12 09:21:46,313 [12] DEBUG Snowflake.Data.Core.SFSession [(null)] - Open Session
2021-08-12 09:21:46,492 [12] INFO  Snowflake.Data.Core.Authenticator.KeyPairAuthenticator [(null)] - Key-pair Authentication
[2021-08-12 09:21:47.06951982021-08-12 09:21:47,181 [12] DEBUG Snowflake.Data.Core.Authenticator.KeyPairAuthenticator [(null)] - Send login request
2021-08-12 09:21:47,292 [12] DEBUG Snowflake.Data.Core.HttpUtil+RetryHandler [(null)] - Http request timeout : 00:00:16
[2021-08-12 09:21:47,296 [12] DEBUG Snowflake.Data.Core.HttpUtil+RetryHandler [(null)] - Rest request timeout : 00:02:00
[2021-08-12 09:21:47.61220602021-08-12 09:21:47,619 [14] DEBUG Snowflake.Data.Core.HttpUtil+RetryHandler [(null)] - Success Response: StatusCode: 200, ReasonPhrase: 'OK'
2021-08-12 09:21:47,655 [14] ERROR Snowflake.Data.Core.SFSession [(null)] - Authentication failed
Error: Incorrect username or password was specified. SqlState: 08006, VendorCode: 390100, QueryId:
 [2021-08-12 09:21:47,697 [4] ERROR Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Unable to connect
Error: Incorrect username or password was specified. SqlState: 08006, VendorCode: 390100, QueryId:
```
The stack trace is:
```
Snowflake.Data.Client.SnowflakeDbException
  HResult=0x80004005
  Message=Snowflake Internal Error: Unable to connect
  Source=Snowflake.Data
  StackTrace:
   at Snowflake.Data.Client.SnowflakeDbConnection.<OpenAsync>b__32_0(Task previousTask)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ESCID.ESP.SnowflakeOperator.Infrastructure.SnowflakeClient.SnowflakeClientFactory.<GetClientAsync>d__4.MoveNext() in {{{REDACTED_PATH_HERE}}}\SnowflakeClientFactory.cs:line 40

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
AggregateException: One or more errors occurred. (Incorrect username or password was specified.)

Inner Exception 2:
SnowflakeDbException: Incorrect username or password was specified.
```

**Comment by anekdoti** [comment]
By comparing the requests to Snowflake submitted by the Snowflake connector running in the operator and in the test, we found the reason: The Snowflake connector serializes the request with the global default settings for the JSON serializer. This global settings seem to be modified by the operator. This changes the casing in the field names of the request in a strange way. E.g.:

**Comment by erin-allison** [comment]
Yep, something like that is pretty much what I was hoping to find. I missed the part where it was only your integration tests passing; I was digging around thinking your operator worked on your machine but not in-cluster.

Probably worth just closing this issue out since it is more specifically defined between the other two you opened above, and I'll see what I can do about the JSON settings on this end.

**Comment by anekdoti** [comment]
You are right. I will close the issue.
