### ISSUE TITLE
Provide ability to alter ComparisonConfig in ResourceCache

### ISSUE THREAD

**Issue by bwarthur** [buehler/dotnet-operator-sdk#364]
**Is your feature request related to a problem? Please describe.**
Some types (particularly ones with circular references) have errors during the comparison inside the ResourceCache.  Below is the error I have been commonly getting:

```
System.Exception: Indexer must have a corresponding Count property that is an integer for object Spec
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.IsValidIndexer(ComparisonConfig config, PropertyEntity info, String breadCrumb)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.StructComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at KubeOps.Operator.Caching.ResourceCache`1.CompareCache(TEntity resource)
   at KubeOps.Operator.Caching.ResourceCache`1.Upsert(TEntity resource, CacheComparisonResult& result)
   at KubeOps.Operator.Controller.ManagedResourceController`1.MapWatchEvent(ValueTuple`2 data)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 188
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at KubeOps.Operator.Kubernetes.ResourceWatcher`1.OnWatcherEvent(WatchEventType type, TEntity resource)
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
```

If I had access to the `ComparisonConfig` I could set it to ignore the invalid indexers and configure custom comparisons (since all my entities have auto generated comparers).

**Describe the solution you'd like**
Any way to be able to configure the comparison would be helpful.  Two possible suggestions I have would be:

- Create a new class with a public static property that is used as the default comparison config.
```
public class ResourceComparisonSettings
{
    private const string ResourceVersion = "ResourceVersion";
    private const string ManagedFields = "ManagedFields";

    public static ComparisonConfig DefaultComparisonConfig { get; set; } = new()
    {
        Caching = true,
        AutoClearCache = false,
        MembersToIgnore = new() { ResourceVersion, ManagedFields }
    };
}
```

- Add an extension method to `OperatorBuilder` to configure settings for the comparison / register a factory in the DI container to create the `ComparisonConfig` object.

If either of these approaches is acceptable, I should have time to get a PR done for the changes.

**Additional context**
This particular error can be reproduced by setting the type for any property (I use `Spec`) on an entity to `JsonElement`.

```csharp
[KubernetesEntity(
    ApiVersion = "v1alpha1",
    Kind = "Cluster",
    Group = "xds",
    PluralName = "clusters")]
public class V1Alpha1Cluster : CustomKubernetesEntity, IStatus<V1Alpha1ClusterStatus>
{
    public V1Alpha1Cluster()
    {
    }

    [PreserveUnknownFields]
    public JsonElement? Spec { get; set; }

    public V1Alpha1ClusterStatus Status { get; set; }
}

public class V1Alpha1ClusterStatus
{

}
```

**Comment by erin-allison** [comment]
Another idea: how about the comparison logic is changed to test if the entity implements `IEquatable<T>` and to call `T.Equals` if it does, otherwise falling back to use of the deep comparison provided by the CompareNetObjects library?
