### ISSUE TITLE
Watcher seems to error on missing objects

### ISSUE THREAD

**Issue by wasabii** [buehler/dotnet-operator-sdk#401]
Getting a mess of these guys. I think this might be because I have no entities of the given type. I'm not getting them for entities I do have at least one object of.

Not sure if something in k8s is supposed to return 404 in the case of no objects. But, if so, it should probably be handled instead of thrown and logged.

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.WatcherExt.<>c__DisplayClass1_0`2.<<MakeStreamReaderCreator>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
[08:25:51 INF] Trying to reconnect with exponential backoff 00:00:32.
```

**Comment by buehler** [comment]
This seems to be happening in the watcher loop. This happens when you try to run an operator with CRDs that are not yet installed in the Kubernetes instance. Then the API returns not found. For CRDs that exist but have no entities, it should not return 404.

**Comment by Silvenga** [comment]
FWIW - this error appears fine - although there is an error logged. We see it when monitoring for DeploymentConfigs (a OpenShift entity) when running within vanilla K8s, and we haven't seen any problems so far.

**Comment by buehler** [comment]
This is normal behavior. If a CRD is not installed in K8S, the watcher will throw an error for those resources.
