### ISSUE TITLE
MyOperator.Entities.V1DemoEntity". Microsoft.Rest.SerializationException: Unable to deserialize the response.

### ISSUE THREAD

**Issue by hemantkathuria** [buehler/dotnet-operator-sdk#460]
I have noticed that the below error occurs until I have created a new custom resource for demo entity type. Once the custom resource is created, this error goes away. Also, I can confirm that no reconcile is getting fired in my democontroller and have no control to catch this error, I believe this needs to be catch in kubeops sdk?

```
fail: KubeOps.Operator.Kubernetes.ResourceWatcher[0] There was an error while watching the resource "MyOperator.Entities.V1DemoEntity". Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0. at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan1 bytes)
at System.Text.Json.Utf8JsonReader.Read()
at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) --- End of inner exception stack trace --- at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex) at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase) at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options) at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo) at System.Text.Json.JsonSerializer.ReadAllUsingOptions[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options) at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options) at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable1 watch, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable1 watch, CancellationToken cancellationToken) at k8s.Kubernetes.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, Nullable1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable1 limit, String resourceVersion, String resourceVersionMatch, Nullable1 timeoutSeconds, Nullable1 watch, Nullable1 pretty, IDictionary2 customHeaders, CancellationToken cancellationToken) at k8s.WatcherExt.<>c__DisplayClass1_02.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at k8s.Watcher1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task1 t)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at k8s.Watcher1.CreateWatchEventEnumerator(Func1 streamReaderCreator, Action1 onError, CancellationToken cancellationToken)+MoveNext()
at k8s.Watcher1.CreateWatchEventEnumerator(Func1 streamReaderCreator, Action1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult() at k8s.Watcher1.WatcherLoop(CancellationToken cancellationToken)
at k8s.Watcher1.WatcherLoop(CancellationToken cancellationToken)
```

**Comment by McSoda** [comment]
Hi all,
Had the same error until I created a corresponding custom resource.
Even after I have deleted the resource, the error didn't reappear.

Hope this helps.

**Comment by coman3** [comment]
> Hi all, Had the same error until I created a corresponding custom resource. Even after I have deleted the resource, the error didn't reappear.
> 
> Hope this helps.

If you restart the pod it will reappear :(

**Comment by buehler** [comment]
Question: do you have the V1 Demo instance still in your source code? The operator does not (as far as I know) install resources on startup. It only starts.

**Comment by coman3** [comment]
So this error occurs with the default generated CRD specs and deployment installed. This error shows on the default "demo project (C#)".

Then, whilst the operator is running - it tries to start a watch for new resources (specifically what we have controllers for - or the DemoController). However, if there are no custom entities registered within kubernetes (but the CRD spec has been installed) this error will occur every 2-3 seconds, until a new resource is created. 

This does not have anything to do with a failed install, or missing CRD specs, and instead a runtime problem with an empty response on the watch call (from what i can tell of that stack trace).

**Comment by buehler** [comment]
hmm... alright. Then all we need to do is to catch this empty response and just ignore it since the operator works correctly

**Comment by buehler** [comment]
![image](https://user-images.githubusercontent.com/1067213/183846481-3264c55b-ffeb-405e-a3bd-c3760e21b39f.png)
now this is more like it...
