### ISSUE TITLE
[bug]: The operator sdk should work with secure images & offline Kubernetes clusters

### ISSUE THREAD

**Issue by virgilp** [buehler/dotnet-operator-sdk#567]
### Describe the bug

```
Download cfssl / cfssljson for linux.
Make unix binaries executable.
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'chmod' with working directory '/operator'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at KubeOps.Operator.Commands.CommandHelpers.CertificateGenerator.<>c__DisplayClass23_0.<ExecuteProcess>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

One cannot rely on executables such as `sh` or `chmod` being present on the image - the fact that the image can execute this particular .net application doesn't mean that the application should download & execute "random" stuff from the internet.  There should be a way to pre-download the binaries that are needed on the image

### To reproduce

Install a local K8s (e.g. enable via docker desktop). Block all outgoing connections to `github.com`, then deploy your operator. 

### Expected behavior

Operator should work without downloading executables from the interenet. The current behaviour is a security bug.

**Comment by virgilp** [comment]
Another problem with current approach: reliability. If github is down, my service is also down even though I had no idea it depends on github. Furthermore, if Cloudflare decides to rename the `cfssl` repository - all kubernetes operators built with this SDK will stop working.

**Comment by virgilp** [comment]
I opened PR #568 to fix this issue
