### ISSUE TITLE
[bug]: Timestamp deserialization fails on well-formatted timestamps depending on number of nanosecond digits

### ISSUE THREAD

**Issue by ndallmeyer** [buehler/dotnet-operator-sdk#599]
### Describe the bug

This is a bug introduced by the KubernetesClient-dependency itself, not a KubeOps-bug itself.

According to the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties), the lastTransitionTimestamp should be deserializable as a Golang Time struct. The deserialization of a string into such a struct follows the conventions of [RFC3339](https://www.rfc-editor.org/rfc/rfc3339.html) and [its implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/time/format.go;l=1494) in particular allows an arbitrary number of nanosecond digits from 0 to 9. However KubernetesClient in versions below 12.0.16 only allowed 3, 6 or 7 digits and was especially struggling with 9 digits. Therefore the recent version of [12.0.16](https://github.com/kubernetes-client/csharp/releases/tag/v12.0.16) KubernetesClient made parsing more tolerant. More details can be found in https://github.com/kubernetes-client/csharp/issues/1350. 

An update to KubernetesClient version [12.0.16](https://github.com/kubernetes-client/csharp/releases/tag/v12.0.16) resolves this issue.

### To reproduce

Create and read a Kubernetes resource with a status condition where the lastTransitionTimestamp has e.g. 9 nanosecond positions. The exception shown below will be thrown.

```
System.FormatException: String '2023-07-26T11:17:34.255606088Z' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, TimeSpan& offset)
   at System.DateTimeOffset.ParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles)
   at k8s.KubernetesJson.KubernetesDateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at k8s.GenericClient.ReadNamespacedAsync[T](String ns, String name, CancellationToken cancel)
```

### Expected behavior

The Kubernetes resource should be read properly, including the lastTransitionTimestamp of the status condition.

**Comment by regme** [comment]
As mentioned 

> More details can be found in https://github.com/kubernetes-client/csharp/issues/1350 
An update to KubernetesClient version [12.0.16](https://github.com/kubernetes-client/csharp/releases/tag/v12.0.16) resolves this issue.

KubernetesClient has been already upgraded to 12.1.1 in yours commit https://github.com/buehler/dotnet-operator-sdk/commit/1c870bf29e3529e27fd32ec19b3b4bb786f40b15

Seems like this bug could be marked as closed.

@buehler

**Comment by tomasfabian** [comment]
Hello, could this Kubernetes client upgrade possibly be released before the major changes coming from the PR ['add conversion webhook,'](https://github.com/buehler/dotnet-operator-sdk/pull/639), please? 
Thank you very much in advance!

**Comment by buehler** [comment]
Hey @tomasfabian 

Actually they are in some pre version of 8.
