### ISSUE TITLE
[bug]: Mutation WebHook throws JsonDiff ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by rajaniraog** [buehler/dotnet-operator-sdk#682]
### Describe the bug

When mutiple Mutation WebHooks are created simultaneously with changes, resulting in modified `MutationResult()`, the 

1. `AdmissionResponse IAdmissionWebhook<TEntity, MutationResult>.TransformResult(MutationResult result, AdmissionRequest<TEntity> request)` invokes `KubernetesJsonDiffer.DiffObjects(from, to);`  gets invoked which then calls `KubernetesJsonDiffer.DiffObjects(from, to);` which isn't thread safe due to using a `static JsonPatchDeltaFormatter Formatter = new();``

### To reproduce

Make simultaneous calls to Mutation WebHooks `MutationResult IAdmissionWebhook<TEntity, MutationResult>.Create(TEntity newEntity, bool dryRun)` results in `System.ArgumentOutOfRangeException`. See additional context below for full callstack.

### Expected behavior

No exception should occur when making simultaneous calls to Mutation WebHooks with a modified `MutationResult()`

### Additional Context

```
An error happened during admission.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than or equal to the size of the collection. (Parameter 'length')
         at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
         at System.Text.Json.JsonDiffPatch.Diffs.Formatters.JsonPatchDeltaFormatter.PropertyPathScope.Dispose()
         at System.Text.Json.JsonDiffPatch.Diffs.Formatters.JsonPatchDeltaFormatter.FormatObjectProperty(JsonDiffDelta& delta, JsonNode left, String propertyName, JsonNode existingValue)
         at System.Text.Json.JsonDiffPatch.Diffs.Formatters.DefaultDeltaFormatter`1.FormatObject(JsonDiffDelta& delta, JsonObject left, TResult existingValue)
         at System.Text.Json.JsonDiffPatch.Diffs.Formatters.DefaultDeltaFormatter`1.FormatJsonDiffDelta(JsonDiffDelta& delta, JsonNode left, TResult existingValue)
         at System.Text.Json.JsonDiffPatch.Diffs.Formatters.DefaultDeltaFormatter`1.Format(JsonDiffDelta& delta, JsonNode left)
         at System.Text.Json.JsonDiffPatch.JsonDiffPatcher.DiffAndFormat[TResult](JsonNode left, JsonNode right, IJsonDiffDeltaFormatter`1 formatter, JsonDiffOptions options)
         at System.Text.Json.JsonDiffPatch.JsonDiffPatcher.Diff[TResult](JsonNode left, JsonNode right, IJsonDiffDeltaFormatter`1 formatter, JsonDiffOptions options)
         at KubeOps.Operator.Webhooks.KubernetesJsonDiffer.DiffObjects(Object from, Object to) in ..\dotnet-operator-sdk-release\src\KubeOps\Operator\Webhooks\KubernetesJsonDiffer.cs:line 18
         at KubeOps.Operator.Webhooks.IMutationWebhook`1.KubeOps.Operator.Webhooks.IAdmissionWebhook<TEntity,KubeOps.Operator.Webhooks.MutationResult>.TransformResult(MutationResult result, AdmissionRequest`1 request, ILogger logger) in ..\dotnet-operator-sdk-release\src\KubeOps\Operator\Webhooks\IMutationWebhook{TEntity}.cs:line 87
         at KubeOps.Operator.Webhooks.IAdmissionWebhook`2.<Register>b__15_0(HttpContext context)
```

**Comment by rajaniraog** [comment]
PR created with fix: https://github.com/buehler/dotnet-operator-sdk/pull/683

**Comment by buehler** [comment]
Hey @rajaniraog 

I can try :)
It will not be easy since the main branch has diverged pretty heavy compared to the release branch. I hoped to release v8 before new year.
