### ISSUE TITLE
Unhandled exception. System.NotSupportedException and then crash and exit

### ISSUE THREAD

**Issue by sabbadino** [buehler/dotnet-operator-sdk#76]
Starting from the sample operator provider in this repo I have slightly modified the entity and create a few instances of my CRD.
cluster is kind (running k8s v1.19.1) 
the operator project is run locally .. when a crd instance is created I get the notification correctly .. however , if I wait a while I get the message
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
      The server closed the connection. Trying to reconnect.

then when the connection is re established i start getting notification again ?! .. and then boom due to the excpetion below  **_Note that the application crash and exit_**

Unhandled exception. trceUnhandled exception. : KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/1".
Unhandled exception. System.NotSupportedException: Dynamic Objects Are Not Supported as TryGetMember requires Microsoft.CSharp which requires .NET Framework 4.5 and higher. ExpandoObjects are supported.
See https://github.com/GregFinzer/Compare-Net-Objects/issues/103

Full stack trace below
---------------
info: KubeOps.Operator.Leadership.LeaderElector[0]
      Startup Leader Elector for operator "kubeops-warehouse".
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetching namespace for leader election.
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetch V1Lease object for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElector[0]
      The instance "DESKTOP-LORENZO" is still the leader for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElection[0]
      Leadership state changed to: Leader.
info: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Startup CRD Controller for "KubeOps.WareHouse.Entities.ProductInfoEntity".
info: KubeOps.Operator.Controller.ResourceControllerBase[0]
      This instance was elected as leader, starting event queue.
dbug: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Event queue startup for type "KubeOps.WareHouse.Entities.ProductInfoEntity".
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Resource Watcher startup for type "KubeOps.WareHouse.Entities.ProductInfoEntity".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Start queue reader for type "KubeOps.WareHouse.Entities.ProductInfoEntity".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/p1".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Resource "productinfoentity/p1" comparison result "New".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Enqueue event "Created" for resource "productinfoentity/p1".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/2".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Read event "Created" for resource "KubeOps.WareHouse.Entities.ProductInfoEntity".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Resource "productinfoentity/2" comparison result "New".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Enqueue event "Created" for resource "productinfoentity/2".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/1".
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Resource "productinfoentity/1" comparison result "New".
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Enqueue event "Created" for resource "productinfoentity/1".
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
dbug: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Execute event "Created" on resource "productinfoentity/p1".
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\bin\Debug\netcoreapp3.1
dbug: KubeOps.WareHouse.TestManager.ProductInfoManager[0]
      Created
fail: KubeOps.WareHouse.Controller.ProductController[0]
      error in ProductInfoEntityCreated
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.CreateNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObject(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty)
   at KubeOps.WareHouse.TestManager.ProductInfoManager.Created(ProductInfoEntity entity) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\TestManager\ProductInfoManager.cs:line 42
   at KubeOps.WareHouse.Controller.ProductController.Created(ProductInfoEntity resource) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\Controller\ProductController.cs:line 32
info: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Event type "Created" on resource "productinfoentity/p1" successfully reconciled. Requeue not requested.
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Read event "Created" for resource "KubeOps.WareHouse.Entities.ProductInfoEntity".
dbug: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Execute event "Created" on resource "productinfoentity/2".
dbug: KubeOps.WareHouse.TestManager.ProductInfoManager[0]
      Created
fail: KubeOps.WareHouse.Controller.ProductController[0]
      error in ProductInfoEntityCreated
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.CreateNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObject(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty)
   at KubeOps.WareHouse.TestManager.ProductInfoManager.Created(ProductInfoEntity entity) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\TestManager\ProductInfoManager.cs:line 42
   at KubeOps.WareHouse.Controller.ProductController.Created(ProductInfoEntity resource) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\Controller\ProductController.cs:line 32
info: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Event type "Created" on resource "productinfoentity/2" successfully reconciled. Requeue not requested.
trce: KubeOps.Operator.Queue.ResourceEventQueue[0]
      Read event "Created" for resource "KubeOps.WareHouse.Entities.ProductInfoEntity".
dbug: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Execute event "Created" on resource "productinfoentity/1".
dbug: KubeOps.WareHouse.TestManager.ProductInfoManager[0]
      Created
fail: KubeOps.WareHouse.Controller.ProductController[0]
      error in ProductInfoEntityCreated
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.CreateNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObject(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String pretty)
   at KubeOps.WareHouse.TestManager.ProductInfoManager.Created(ProductInfoEntity entity) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\TestManager\ProductInfoManager.cs:line 42
   at KubeOps.WareHouse.Controller.ProductController.Created(ProductInfoEntity resource) in E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\Controller\ProductController.cs:line 32
info: KubeOps.Operator.Controller.ResourceControllerBase[0]
      Event type "Created" on resource "productinfoentity/1" successfully reconciled. Requeue not requested.
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetch V1Lease object for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElector[0]
      The instance "DESKTOP-LORENZO" is still the leader for operator "kubeops-warehouse".
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetch V1Lease object for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElector[0]
      The instance "DESKTOP-LORENZO" is still the leader for operator "kubeops-warehouse".
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetch V1Lease object for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElector[0]
      The instance "DESKTOP-LORENZO" is still the leader for operator "kubeops-warehouse".
trce: KubeOps.Operator.Leadership.LeaderElector[0]
      Fetch V1Lease object for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Leadership.LeaderElector[0]
      The instance "DESKTOP-LORENZO" is still the leader for operator "kubeops-warehouse".
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
      The server closed the connection. Trying to reconnect.
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Restarting resource watcher for type "KubeOps.WareHouse.Entities.ProductInfoEntity".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/p1".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/2".
Unhandled exception. trceUnhandled exception. : KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Added" for "productinfoentity/1".
Unhandled exception. System.NotSupportedException: Dynamic Objects Are Not Supported as TryGetMember requires Microsoft.CSharp which requires .NET Framework 4.5 and higher. ExpandoObjects are supported.
See https://github.com/GregFinzer/Compare-Net-Objects/issues/103
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.HandleDynamicObject(ComparisonConfig config, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.GetCurrentProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at KubeOps.Operator.Caching.ResourceCache`1.CompareCache(TEntity resource)
   at KubeOps.Operator.Caching.ResourceCache`1.Upsert(TEntity resource, CacheComparisonResult& result)
   at KubeOps.Operator.Queue.ResourceEventQueue`1.Enqueue(TEntity resource, Nullable`1 enqueueDelay)
   at KubeOps.Operator.Queue.ResourceEventQueue`1.OnWatcherEvent(Object _, ValueTuple`2 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.NotSupportedException: Dynamic Objects Are Not Supported as TryGetMember requires Microsoft.CSharp which requires .NET Framework 4.5 and higher. ExpandoObjects are supported.
See https://github.com/GregFinzer/Compare-Net-Objects/issues/103
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.HandleDynamicObject(ComparisonConfig config, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.GetCurrentProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at KubeOps.Operator.Caching.ResourceCache`1.CompareCache(TEntity resource)
   at KubeOps.Operator.Caching.ResourceCache`1.Upsert(TEntity resource, CacheComparisonResult& result)
   at KubeOps.Operator.Queue.ResourceEventQueue`1.Enqueue(TEntity resource, Nullable`1 enqueueDelay)
   at KubeOps.Operator.Queue.ResourceEventQueue`1.OnWatcherEvent(Object _, ValueTuple`2 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
E:\_sabba-dev\k8sWareHouse\KubeOps.WareHouseOperator\bin\Debug\netcoreapp3.1\KubeOps.WareHouse.exe (process 17960) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by buehler** [comment]
Outch.

First of all, the 
```
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
The server closed the connection. Trying to reconnect.
```
part is normal. The resource watcher (from the original kubernetes client lib) has a timeout setting. If this is set too wide, everything falls apart. I set it to be 1minute. 

After this minute, the server will terminate the resource watcher. This is an expected behaviour and will automatically restart the watcher. What *shouldn't* happen though is the crash that you are seeing.

My wild guess is, that the compare net objects is crashing. But the weird thing is, there aren't any `dynamics` in this code. 🤔 

I'll have a look at the error message, maybe I need to change some things with the compare logic.

The notification for the new watcher will be a `not changed` as I'm aware of.

**Comment by buehler** [comment]
Are you using .net framework or .net core?

**Comment by sabbadino** [comment]
Netcore 3.1

**Comment by buehler** [comment]
It seems to be a problem with the 
```
Execute event "Created" on resource "productinfoentity/1".
dbug: KubeOps.WareHouse.TestManager.ProductInfoManager[0]
Created
fail: KubeOps.WareHouse.Controller.ProductController[0]
error in ProductInfoEntityCreated
```
productinfoentity
in the controller. I guess you're doing some kind of update in the controller?
The program throws a NotFound. The second entity (`productinfoentity/1`) works fine.

Do you have this code online somewhere?

And yea, `dynamic` is not supported as it seems from CompareNetObjects

**Comment by sabbadino** [comment]
The dynamic object is a jobject that implement IDynamicMetaObjectProvider and compareobjects tests this interface to decide if it is dynamic.
Currently i am passing a jobject when creating a crd instance.. i can change that ,but on the reason side i see a call to safejsonhelper.deserializeobject<object> .. i cannot change that .. and i guess (had no time to test ) that a jobject is returned (i will let you know soon).
Maybe when comparing objects you could serialize them as string and check for string equality.
Or you might want to give a try to 
Fluent assertion nuget package and use 
orderDto.Should().BeEquivalentTo(order)

**Comment by sabbadino** [comment]
As a "quick" ?  fix I locally modified CompareCache to ignore Metadata.ManagedFields :
  new ComparisonConfig
            {
                Caching = true,
                AutoClearCache = false,
                MembersToIgnore = new List<string> { ResourceVersion , **"ManagedFields"** },
            });


Additionally, I added in ResourceEventQueue.OnWatcherEvent a try catch to avoid the process to go down
try {.. 
}
catch (Exception ex)
            {
                _logger.LogError(ex,$"Error in{nameof(OnWatcherEvent)}: {ex}");
            }

**Comment by buehler** [comment]
hmmm I never heard of those ManangedFields before, are they new? Did they flew in with k8s 1.19?
If so, what is the purpose of them? Maybe we can just ignore them.

**Comment by sabbadino** [comment]
They are related to server side apply ..
They were introduced in k8s 1.18 as far i understand.

https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/

**Comment by sabbadino** [comment]
As you have likely understood, until this has not be fixed somehow, the operator process will crush regularly after first connection lost with k8s cluster greater or equal 1.18.
